# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO08DD34ptkX24atCBoAVogKTpVIOhPA
"""

# 1. Standard Imports
import torch
from diffusers import DiffusionPipeline, DPMSolverMultistepScheduler
from diffusers.utils import export_to_video
from moviepy.video.io.VideoFileClip import VideoFileClip
from moviepy.video.compositing.concatenate import concatenate_videoclips
from google.colab import files
import os

# 2. Setup (Increased num_inference_steps for better detail)
print("⏳ Loading High-Quality Model...")
pipe = DiffusionPipeline.from_pretrained("damo-vilab/text-to-video-ms-1.7b", torch_dtype=torch.float16, variant="fp16")
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe.to("cuda")
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()

def generate_hq_10_sec_video():
    prompt = input("Enter your prompt (e.g., 'Cinematic 4k shot of a lion'): ")

    # QUALITY TIP: A negative prompt helps the AI avoid common errors
    negative_prompt = "low quality, blurry, distorted, static, noisy, shutterstock watermark, grainy"

    num_clips = 5
    clip_files = []

    print(f"🎬 Generating HQ 10-second video...")

    for i in range(num_clips):
        print(f"🔄 Processing Segment {i+1}/5 (Higher detail)...")

        # QUALITY CHANGE: num_inference_steps=50 (up from 25) for more detail
        video_frames = pipe(
            prompt,
            negative_prompt=negative_prompt,
            num_inference_steps=50,
            num_frames=16,
            guidance_scale=9.0 # Higher scale makes it follow your prompt more strictly
        ).frames[0]

        temp_name = f"hq_clip_{i}.mp4"
        export_to_video(video_frames, output_video_path=temp_name)
        clip_files.append(temp_name)

    # 3. Final Stitching
    clips = [VideoFileClip(f) for f in clip_files]
    final_video = concatenate_videoclips(clips, method="compose")
    final_video.write_videofile("final_hq_video.mp4", fps=16, codec="libx264")

    files.download("final_hq_video.mp4")
    for c in clips: c.close()
    for f in clip_files: os.remove(f)

generate_hq_10_sec_video()